### PR TITLE
Haskell Start Croatian

### PR DESCRIPTION
**Pull request by diomed**

### CODE REVIEW

**Comment by diomed** [comment]
⁉️

**Comment by diomed** [comment]
⁉️

**Comment by bitemyapp** [comment]
@diomed apologies for not getting back to you sooner! I'll merge this and see if I can have someone take a look at it later.

Thank you so much for this!

**Comment by diomed** [comment]
no problem. this was actually done by following Serbian version.
since Serbian and Croatian are alike. so it's as accurate as that one.
still, it's nice to be able to read it in our own language, so I made adjustments for it.

**Review by sins921 — APPROVED** [review]

**Pull request merged**
