### PR TITLE
German Translation

### PR DESCRIPTION
**Pull request by jhedev**
Here is the german version of the guide after my first iteration. I think there is still some space for improvements because some parts are not really good German style and sound a bit weird at the moment. So *please do not merge yet*.

I'll try to do the improvements in the next few days and maybe I can find a few other Germans to help me.

There are still a lot of English words in it, which has different reasons:

* some words, for which I would use the English term when speaking German also , e.g. Laziness or sandbox
* technical terms, especially in type or category theory, like catamorphism. I'm just not sure how these are called in German.
* Titles of books/articles/etc. If you used the English title of a reference when linking to it, I did not translate it because I think this is somewhat confusing (would be interesting how the others see this, maybe discuss in #51? ).

Well, that's it for now :)

### CODE REVIEW

**Comment by bitemyapp** [comment]
Reasons you gave for using English in various spots makes sense. I'll leave this up until you give me the word.

**Comment by jhedev** [comment]
Two things that came up while getting feedback from others and might also interest you:

* It is not really clear what `cabal hell` actually means, at least for absolute beginners. This applies to both the German and English version currently. Maybe adding a sentence to clarify this would be sufficient.
* It is somewhat unfortunate that the guide is now available in German but all references are still English. I added a note about this at the beginning. Maybe we could also add a section with some german resources. I know at least two useful ones:
  * [funktionale-programmierung.de](http://funktionale-programmierung.de/tags-archive.html#Haskell) is a blog about functional programming which includes a few posts about Haskell with various topics from beginner to more advanced stuff
  * [Course notes](http://verify.rwth-aachen.de/fp14/FP14.pdf) of a course about functional programming with a brief introduction to Haskell and chapters about the lambda calculus and type inference.

Any thoughts?

**Comment by bitemyapp** [comment]
@jhedev A language-specific section after the install instructions & primary course could work.

NICTA course is relatively language agnostic, but without cis194 as a warm-up, could be pretty difficult for self-learners.

**Comment by jhedev** [comment]
I added the language-specific section as you suggested. From my side it's now ready to merge :)

**Comment by bitemyapp** [comment]
@jhedev Thank you, this is awesome! :bear: :sunglasses:

**Pull request merged**
