### PR TITLE
Add instructions suitable for FreeBSD and similar.

### PR DESCRIPTION
**Pull request by mwm**
Not clear what other systems have people maintaining GHC & Cabal packages, but that's the place to start for most other people.

### CODE REVIEW

**Comment by bitemyapp** [comment]
@mwm Cabal installing alex & happy into your user package-db will only work if ~/.cabal/bin is in your $PATH.

**Comment by mwm** [comment]
@bitemyapp good catch. Fixed. Also added instructions to update cabal-install to save the readers a step.

**Comment by bitemyapp** [comment]
@mwm why are there add'l spaces in lines 209-214?

**Comment by bitemyapp** [comment]
Thank you @mwm !

:smile_cat:

**Pull request merged**
