### PR TITLE
korean 15/09/23

### PR DESCRIPTION
**Pull request by steelbear**
Korean translation - readme.md

### CODE REVIEW

**Comment by bitemyapp** [comment]
@steelbear sorry for not checking in sooner, do you consider this good to go or do you want somebody to review it still?

**Comment by steelbear** [comment]
I want to recheck it. But I am busy now. It takes some time.

**Comment by bitemyapp** [comment]
@steelbear no problem and no pressure. Just ping me when you're ready :)

**Comment by bitemyapp** [comment]
@steelbear going forward with this, thank you!

**Pull request merged**
