### PR TITLE
Ukrainian translation of the guide.

### PR DESCRIPTION
**Pull request by fester**
This pull request contains translation of the guide and list of specific topics into Ukrainian.

### CODE REVIEW

**Comment by bitemyapp** [comment]
Wow even the specific topics too! Thank you! :smile: 

Is this ready to merge @fester?

**Comment by fester** [comment]
I'd say it's ready now, but I was the only person to proofread the text and there's a non-zero chance of having at least stylistic errors. My proposition is to merge it so I'll call my friends to go through the text and suggest edits.

**Comment by bitemyapp** [comment]
@fester sounds good, thank you!

**Comment by fester** [comment]
Thanks for bringing the list together :)

**Pull request merged**
