### PR TITLE
Updated links to CIS194 from Spring 2013 to Spring 2015

### PR DESCRIPTION
**Pull request by NickAger**

### CODE REVIEW

**Comment by bitemyapp** [comment]
Not without pedagogical justification, it being on 2013 was not an oversight - it was intentional.

Explanation here: http://bitemyapp.com/posts/2014-12-31-functional-education.html

**Comment by NickAger** [comment]
Its the same course - but slightly more polished

**Comment by bitemyapp** [comment]
@NickAger it's not polished, it's targeting a different set of topics entirely and is no longer an introduction to the basics which is the purpose cis194 Spring 13 serves. Did you read the bits on cis194 in the post I linked?

It's entirely possible we could link a newer version of cis194 but it would overlap with cs240h and we'd have to slice & dice the redundant bits and would *still* need Spring 13 cis194 to cover basics and some other topics.

**Comment by NickAger** [comment]
Apologies - I am learning Haskell and I have found your "functional education" post really useful. I must admit I did miss your emphasis of cis194 Spring 13 over Spring 14 or 15. However i am following Spring 15 (on lecture 5) and found the lectures sparse but the exercises excellent. I just assumed that lectures really needed supplementing with LYAH or RWH. I have found that the exercises are finally providing the challenge and motivation I needed to feel I’m making progress - after a couple of false starts attempting to learn Haskell. However I do miss a forum where more experienced Haskell developers could critic my code. 
Thanks for the detailed explanation and I look forward to reading your book when it comes out

**Comment by bitemyapp** [comment]
@NickAger the process you describe there makes sense, but we're trying to avoid people needing to get the basics from LYAH or RWH, the post explains why. Glad you're finding the material useful and making progress. If you could send me an email when you've reached some sort of milestone in your progress I'd love to hear what resources you've used, what's worked, what hasn't - I'd really appreciate it. Cheers :)

**Pull request closed without merging**
